# Generated by Django 3.0.3 on 2020-03-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0002_class_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='isApproved',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
