# Generated by Django 3.0.3 on 2020-03-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0003_baseuser_isapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='course_id',
            new_name='course_title',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='isApproved',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='yes', max_length=128),
        ),
    ]
