# Generated by Django 3.0.3 on 2020-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0006_auto_20200320_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinesAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplines_area', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructordisciplinesareas',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='ClassDisciplinesAreas',
        ),
        migrations.DeleteModel(
            name='InstructorDisciplinesAreas',
        ),
        migrations.AddField(
            model_name='class',
            name='class_disciplines_area',
            field=models.ManyToManyField(to='ADTAA.DisciplinesAreas'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='class_disciplines_area',
            field=models.ManyToManyField(to='ADTAA.DisciplinesAreas'),
        ),
    ]
