# Generated by Django 3.0.3 on 2020-03-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0007_auto_20200321_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_disciplines_area',
            new_name='disciplines_area',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='class_disciplines_area',
            new_name='disciplines_area',
        ),
    ]
