# Generated by Django 3.0.3 on 2020-03-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0009_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='last_name',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='course_title',
            new_name='instructor_id',
        ),
    ]
