# Generated by Django 3.0.3 on 2020-03-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0010_auto_20200329_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='course_number',
            field=models.ManyToManyField(to='ADTAA.Class'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='instructor_id',
            field=models.ManyToManyField(to='ADTAA.Instructor'),
        ),
    ]
