# Generated by Django 3.0.3 on 2020-03-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0011_auto_20200329_0124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
