# Generated by Django 3.0.4 on 2020-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0013_auto_20200331_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='assigned_instructor',
            field=models.CharField(default='No Instructor', max_length=128),
        ),
    ]
